name: 'Localiztion-Management'
author: 'Novaday'
description: 'Localiztion Management'

inputs:
  input_file:
    description: 'The Excell file'
    required: true

runs:
  using: 'composite'
  steps:
    - name: install  
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
      
    - run: python ${{ github.action_path }}/convert.py -input ${{ inputs.input_file }}
      shell: bash
